import { IKBRule } from "@/types/knowledge-base";

export const accessibilityRules: IKBRule[] = [
  {
    ruleId: "A11Y-001",
    ruleName: "Images Missing Alt Text",
    category: "accessibility",
    description: "Images lack descriptive alt attributes for screen reader users",
    whyItMatters: "WCAG 2.1 Success Criterion 1.1.1 requires all non-decorative images to have text alternatives. Screen readers rely on alt text to describe images to visually impaired users.",
    detectionKey: "accessibility.images.missingAlt",
    detectionCondition: { operator: "greater_than", value: 0 },
    recommendation: "Add meaningful alt text to every non-decorative image.",
    implementationSteps: [
      "Audit all <img> elements for missing alt attributes.",
      "Write concise descriptions of what each image shows.",
      "For decorative images, use empty alt=\"\" (not omitting the attribute).",
      "Avoid starting with 'Image of' or 'Picture of' — be direct."
    ],
    codeSnippet: {
      code: '<!-- Meaningful image -->\n<img src="/team.jpg" alt="Development team collaborating in the office" />\n\n<!-- Decorative image -->\n<img src="/divider.svg" alt="" role="presentation" />',
      language: "html"
    },
    aiPromptTemplate: "Write alt text for the images on my page at {url}. Follow WCAG 2.1 guidelines — be descriptive, concise, and avoid redundant phrases.",
    expectedResult: "WCAG 2.1 Level A compliance for non-text content and improved screen reader experience.",
    seoImpact: "Medium",
    googleVisibilityImpact: "Medium",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "High",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 100,
    evidenceSource: "WCAG 2.1 — Non-text Content (Success Criterion 1.1.1)",
    evidenceUrl: "https://www.w3.org/TR/WCAG21/#non-text-content",
    referenceType: "WCAG 2.1",
    penaltyPoints: 20,
    priority: "high"
  },
  {
    ruleId: "A11Y-002",
    ruleName: "Form Inputs Missing Labels",
    category: "accessibility",
    description: "Form input elements have no associated label or aria-label",
    whyItMatters: "WCAG 2.1 Success Criterion 3.3.2 requires form inputs to have labels or instructions. Without them, screen reader users cannot determine what information to enter in each field.",
    detectionKey: "accessibility.forms.labelsCount",
    detectionCondition: { operator: "equals", value: 0 },
    recommendation: "Add <label> elements or aria-label attributes to all form inputs.",
    implementationSteps: [
      "Identify all <input>, <select>, and <textarea> elements.",
      "Add a <label> element with a 'for' attribute matching the input's 'id'.",
      "Alternatively, use aria-label or aria-labelledby for visual-only labels.",
      "Ensure placeholder text is not used as the sole label."
    ],
    codeSnippet: {
      code: '<label for="email">Email Address</label>\n<input type="email" id="email" name="email" />\n\n<!-- Or with aria-label -->\n<input type="search" aria-label="Search the site" />',
      language: "html"
    },
    aiPromptTemplate: "Add proper labels to all form inputs on {url}. Follow WCAG 2.1 guidelines. The forms include {formDescription}.",
    expectedResult: "Screen reader users can clearly identify and interact with all form fields.",
    seoImpact: "None",
    googleVisibilityImpact: "None",
    aiVisibilityImpact: "None",
    accessibilityImpact: "High",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "15 minutes",
    confidenceLevel: 100,
    evidenceSource: "WCAG 2.1 — Labels or Instructions (Success Criterion 3.3.2)",
    evidenceUrl: "https://www.w3.org/TR/WCAG21/#labels-or-instructions",
    referenceType: "WCAG 2.1",
    penaltyPoints: 15,
    priority: "high"
  },
  {
    ruleId: "A11Y-003",
    ruleName: "Positive Tabindex Values",
    category: "accessibility",
    description: "Elements use positive tabindex values that disrupt natural tab order",
    whyItMatters: "WCAG 2.1 Success Criterion 2.4.3 requires keyboard focus order to be logical. Positive tabindex values (1, 2, 3...) override the natural DOM order, creating confusing navigation for keyboard users.",
    detectionKey: "accessibility.keyboardNavigation.hasPositiveTabIndex",
    detectionCondition: { operator: "equals", value: true },
    recommendation: "Remove positive tabindex values. Use tabindex=\"0\" or tabindex=\"-1\" only.",
    implementationSteps: [
      "Search for tabindex attributes with values greater than 0.",
      "Remove them or change to tabindex=\"0\" (natural tab order).",
      "Use tabindex=\"-1\" for elements that should be focusable via JavaScript only.",
      "Rely on DOM order to control the tab sequence."
    ],
    aiPromptTemplate: "Find and fix all positive tabindex values on {url}. Replace with proper keyboard navigation using tabindex=\"0\" and DOM ordering.",
    expectedResult: "Logical keyboard navigation that follows the visual layout of the page.",
    seoImpact: "None",
    googleVisibilityImpact: "None",
    aiVisibilityImpact: "None",
    accessibilityImpact: "Medium",
    securityImpact: "None",
    businessImpact: "Low",
    difficulty: "Medium",
    estimatedFixTime: "15 minutes",
    confidenceLevel: 100,
    evidenceSource: "WCAG 2.1 — Focus Order (Success Criterion 2.4.3)",
    evidenceUrl: "https://www.w3.org/TR/WCAG21/#focus-order",
    referenceType: "WCAG 2.1",
    penaltyPoints: 10,
    priority: "medium"
  },
  {
    ruleId: "A11Y-004",
    ruleName: "Missing ARIA Landmarks",
    category: "accessibility",
    description: "No ARIA landmark roles (main, navigation, banner, etc.) found in HTML",
    whyItMatters: "WCAG 2.1 Success Criterion 2.4.1 requires mechanisms to bypass repeated content blocks. ARIA landmarks allow screen reader users to jump directly to navigation, main content, or footer sections.",
    detectionKey: "accessibility.aria.hasAriaLandmarks",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Add ARIA landmark roles to major structural elements of the page.",
    implementationSteps: [
      "Add role=\"banner\" to the site header (or use <header>).",
      "Add role=\"navigation\" to navigation menus (or use <nav>).",
      "Add role=\"main\" to the primary content area (or use <main>).",
      "Add role=\"contentinfo\" to the footer (or use <footer>).",
      "Use semantic HTML5 elements which have implicit ARIA roles."
    ],
    codeSnippet: {
      code: '<header role="banner">\n  <nav role="navigation"><!-- Nav links --></nav>\n</header>\n<main role="main">\n  <!-- Page content -->\n</main>\n<footer role="contentinfo">\n  <!-- Footer -->\n</footer>',
      language: "html"
    },
    aiPromptTemplate: "Add ARIA landmark roles to the page structure at {url}. Use semantic HTML5 elements where possible.",
    expectedResult: "Screen reader users can quickly navigate between major page sections.",
    seoImpact: "None",
    googleVisibilityImpact: "None",
    aiVisibilityImpact: "None",
    accessibilityImpact: "Medium",
    securityImpact: "None",
    businessImpact: "Low",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 95,
    evidenceSource: "WCAG 2.1 — Bypass Blocks (Success Criterion 2.4.1)",
    evidenceUrl: "https://www.w3.org/TR/WCAG21/#bypass-blocks",
    referenceType: "WCAG 2.1",
    penaltyPoints: 8,
    priority: "medium"
  }
];
