import { IKBRule } from "@/types/knowledge-base";

export const aeoRules: IKBRule[] = [
  {
    ruleId: "AEO-001",
    ruleName: "Missing FAQ Schema Markup",
    category: "aeo",
    description: "Page has question-like content but lacks FAQPage JSON-LD schema",
    whyItMatters: "FAQPage schema enables Google to display expandable FAQ rich results directly in search. It also feeds content into AI Overviews and voice assistants, increasing your content's citation probability.",
    detectionKey: "aeo.faq.hasFaqSchema",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Add FAQPage JSON-LD schema for your Q&A content.",
    implementationSteps: [
      "Identify the core Q&As visible on your page.",
      "Create a FAQPage JSON-LD markup block with mainEntity array.",
      "Each question must have @type: Question with an acceptedAnswer.",
      "Inject the schema inside a <script type=\"application/ld+json\"> tag.",
      "Validate with Google's Rich Results Test."
    ],
    codeSnippet: {
      code: '<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "FAQPage",\n  "mainEntity": [{\n    "@type": "Question",\n    "name": "What services do you offer?",\n    "acceptedAnswer": {\n      "@type": "Answer",\n      "text": "We offer comprehensive web development, SEO optimization, and digital marketing services."\n    }\n  }]\n}\n</script>',
      language: "json"
    },
    aiPromptTemplate: "Generate FAQPage JSON-LD schema markup for the page at {url}. Extract questions and answers from the existing content.",
    expectedResult: "Eligibility for FAQ rich results in Google Search and increased AI citation probability.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — FAQ Structured Data",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/structured-data/faqpage",
    referenceType: "Google Search Central",
    penaltyPoints: 15,
    priority: "high"
  },
  {
    ruleId: "AEO-002",
    ruleName: "No FAQ or Q&A Section",
    category: "aeo",
    description: "Page lacks question-and-answer style content sections",
    whyItMatters: "FAQ sections directly target conversational and voice search queries. Pages with clear Q&A formats are more likely to be featured in Google's AI Overviews and voice assistant responses.",
    detectionKey: "aeo.faq.questionMatches",
    detectionCondition: { operator: "less_than", value: 3 },
    recommendation: "Add a dedicated FAQ section with 3-5 relevant questions and concise answers.",
    implementationSteps: [
      "Research common questions your target audience asks (use Google's 'People Also Ask').",
      "Create 3-5 question-answer pairs relevant to your page topic.",
      "Format questions as H2 or H3 headings.",
      "Provide direct, concise answers (30-55 words) immediately after each question.",
      "Add FAQPage schema markup for the Q&A content."
    ],
    aiPromptTemplate: "Generate 5 FAQ questions and answers for a page about {topic} at {url}. Make answers concise (30-55 words) and conversational.",
    expectedResult: "Increased visibility in voice search results and Google AI Overviews.",
    seoImpact: "Medium",
    googleVisibilityImpact: "Medium",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Medium",
    estimatedFixTime: "30 minutes",
    confidenceLevel: 90,
    evidenceSource: "Google Search Central — Featured Snippets",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/featured-snippets",
    referenceType: "Industry Best Practice",
    penaltyPoints: 10,
    priority: "medium"
  },
  {
    ruleId: "AEO-003",
    ruleName: "Missing Speakable Schema",
    category: "aeo",
    description: "No SpeakableSpecification schema markup found on the page",
    whyItMatters: "Speakable schema identifies sections of your page suitable for text-to-speech rendering by smart speakers and voice assistants like Google Assistant.",
    detectionKey: "aeo.speakable.exists",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Add SpeakableSpecification schema to highlight text-to-speech-ready sections.",
    implementationSteps: [
      "Identify the main headline and lead paragraph sections.",
      "Create a Speakable schema block with CSS selectors pointing to those sections.",
      "Inject the markup in the page head."
    ],
    codeSnippet: {
      code: '<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "WebPage",\n  "name": "Page Title",\n  "speakable": {\n    "@type": "SpeakableSpecification",\n    "cssSelector": [".main-headline", ".lead-paragraph"]\n  }\n}\n</script>',
      language: "json"
    },
    aiPromptTemplate: "Generate SpeakableSpecification schema for the page at {url}. Identify the best sections for text-to-speech.",
    expectedResult: "Voice assistants can identify and read your content aloud to users.",
    seoImpact: "Low",
    googleVisibilityImpact: "Low",
    aiVisibilityImpact: "Medium",
    accessibilityImpact: "Medium",
    securityImpact: "None",
    businessImpact: "Low",
    difficulty: "Easy",
    estimatedFixTime: "5 minutes",
    confidenceLevel: 85,
    evidenceSource: "Schema.org — SpeakableSpecification",
    evidenceUrl: "https://schema.org/SpeakableSpecification",
    referenceType: "Schema.org",
    penaltyPoints: 5,
    priority: "low"
  },
  {
    ruleId: "AEO-004",
    ruleName: "No Structured Lists or Tables",
    category: "aeo",
    description: "Page content lacks HTML list elements (ul/ol) and tables",
    whyItMatters: "Featured snippets and AI search citations strongly favor structured content formats. Lists and tables are the most commonly featured formats in Google's Featured Snippets.",
    detectionKey: "aeo.elements.hasLists",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Add structured lists or comparison tables to organize key information.",
    implementationSteps: [
      "Identify content that could be formatted as steps, features, or comparisons.",
      "Convert sequential content to ordered lists (<ol>).",
      "Convert feature/benefit lists to unordered lists (<ul>).",
      "Use comparison tables for multi-attribute data."
    ],
    codeSnippet: {
      code: "<h2>How to Get Started</h2>\n<ol>\n  <li>Step 1: Sign up for an account</li>\n  <li>Step 2: Configure your settings</li>\n  <li>Step 3: Launch your first project</li>\n</ol>",
      language: "html"
    },
    aiPromptTemplate: "Identify content on {url} that could be restructured into HTML lists or tables for better featured snippet eligibility.",
    expectedResult: "Higher probability of appearing in Google Featured Snippets and AI Overview citations.",
    seoImpact: "Medium",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Medium",
    estimatedFixTime: "15 minutes",
    confidenceLevel: 90,
    evidenceSource: "Google Search Central — Featured Snippets",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/featured-snippets",
    referenceType: "Google Search Central",
    penaltyPoints: 12,
    priority: "medium"
  },
  {
    ruleId: "AEO-005",
    ruleName: "Missing Question-Based Headings",
    category: "aeo",
    description: "No headings match conversational question patterns",
    whyItMatters: "Users search with natural language questions. Heading tags formatted as questions directly match these queries, making your content more likely to be selected as a direct answer by Google and AI models.",
    detectionKey: "aeo.conversational.questionHeadingsCount",
    detectionCondition: { operator: "equals", value: 0 },
    recommendation: "Rewrite some H2/H3 headings as natural questions that users would search for.",
    implementationSteps: [
      "Review your existing H2 and H3 headings.",
      "Rewrite them in question format (e.g., 'Our Services' → 'What services do we offer?').",
      "Follow each question heading with a direct, concise answer in the first paragraph.",
      "Use 'How', 'What', 'Why', 'When', 'Where' question starters."
    ],
    aiPromptTemplate: "Rewrite these headings as conversational questions while preserving the topic: {headings}",
    expectedResult: "Content directly matches voice search and conversational AI queries, increasing citation probability.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 85,
    evidenceSource: "Google Featured Snippets & People Also Ask Optimization",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/featured-snippets",
    referenceType: "Industry Best Practice",
    penaltyPoints: 15,
    priority: "high"
  }
];
