import { IKBRule } from "@/types/knowledge-base";

export const geoRules: IKBRule[] = [
  {
    ruleId: "GEO-001",
    ruleName: "AI Scrapers Blocked in robots.txt",
    category: "geo",
    description: "Robots.txt blocks AI search crawlers like GPTBot or ClaudeBot",
    whyItMatters: "Blocking AI crawlers like GPTBot, ClaudeBot, or Google-Extended prevents your content from being parsed and cited in conversational AI search answers (ChatGPT, Claude, Gemini AI Overviews).",
    detectionKey: "ai_visibility.aiCrawlerBlocking.blockedAiCrawlers",
    detectionCondition: { operator: "not_equals", value: [] },
    recommendation: "Review your robots.txt and allow AI crawlers access to maximize citation opportunities.",
    implementationSteps: [
      "Open your robots.txt file.",
      "Remove Disallow statements targeting AI scrapers (GPTBot, ClaudeBot, Google-Extended, etc.).",
      "Add explicit Allow rules for AI crawlers you want to support.",
      "Keep blocking only for genuinely private content."
    ],
    codeSnippet: {
      code: "User-agent: GPTBot\nAllow: /\n\nUser-agent: ClaudeBot\nAllow: /\n\nUser-agent: Google-Extended\nAllow: /",
      language: "txt"
    },
    aiPromptTemplate: "Review and update my robots.txt to allow AI search crawlers while keeping appropriate restrictions for private content.",
    expectedResult: "Your content becomes eligible for citation in ChatGPT, Claude, and Google AI Overviews.",
    seoImpact: "Low",
    googleVisibilityImpact: "None",
    aiVisibilityImpact: "Critical",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Easy",
    estimatedFixTime: "2 minutes",
    confidenceLevel: 100,
    evidenceSource: "OpenAI GPTBot Documentation",
    evidenceUrl: "https://platform.openai.com/docs/bots/overview",
    referenceType: "Industry Best Practice",
    penaltyPoints: 25,
    priority: "high"
  },
  {
    ruleId: "GEO-002",
    ruleName: "Missing llms.txt File",
    category: "geo",
    description: "No llms.txt file found at the domain root",
    whyItMatters: "llms.txt is an emerging standard that provides LLMs with a clean, markdown-formatted summary of your website structure and content, making it easier for AI models to understand and cite your site.",
    detectionKey: "ai_visibility.llmsTxt.exists",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Create an llms.txt file at your domain root with a structured summary of your site.",
    implementationSteps: [
      "Create a file named 'llms.txt' in your public folder root.",
      "Write a markdown-formatted summary of your site structure.",
      "List key pages with short descriptions.",
      "Deploy and verify at yourdomain.com/llms.txt."
    ],
    codeSnippet: {
      code: "# Your Brand Name\n\n> Brief description of what your company does.\n\n## Pages\n\n- [Home](/): Main landing page with overview of services\n- [About](/about): Company history and team information\n- [Services](/services): Detailed service offerings\n- [Contact](/contact): Contact information and form",
      language: "markdown",
      filename: "llms.txt"
    },
    aiPromptTemplate: "Generate an llms.txt file for my website at {url}. Include a site description and list of key pages with summaries.",
    expectedResult: "AI models can better understand your site structure, increasing the probability of accurate citations.",
    seoImpact: "Low",
    googleVisibilityImpact: "None",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 80,
    evidenceSource: "llms.txt Specification",
    evidenceUrl: "https://llmstxt.org/",
    referenceType: "Industry Best Practice",
    penaltyPoints: 15,
    priority: "medium"
  },
  {
    ruleId: "GEO-003",
    ruleName: "No Outbound Citation Links",
    category: "geo",
    description: "Page contains zero outbound links to external sources",
    whyItMatters: "Citing authoritative external sources demonstrates expertise and builds trust. Google's E-E-A-T guidelines value pages that reference primary sources, and AI models evaluate outbound linking for content reliability assessment.",
    detectionKey: "ai_visibility.citationReadiness.externalLinksCount",
    detectionCondition: { operator: "equals", value: 0 },
    recommendation: "Add outbound links to authoritative sources that support your content claims.",
    implementationSteps: [
      "Identify factual claims or data points in your content.",
      "Link to the original source (research papers, official docs, industry reports).",
      "Use descriptive anchor text for outbound links.",
      "Aim for 2-5 quality external links per page."
    ],
    aiPromptTemplate: "Identify claims in my content at {url} that should cite external sources, and suggest authoritative sources to link to.",
    expectedResult: "Improved E-E-A-T signals and higher content trustworthiness for both Google and AI models.",
    seoImpact: "Medium",
    googleVisibilityImpact: "Medium",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Low",
    difficulty: "Easy",
    estimatedFixTime: "15 minutes",
    confidenceLevel: 85,
    evidenceSource: "Google E-E-A-T Quality Rater Guidelines",
    evidenceUrl: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content",
    referenceType: "Google Search Central",
    penaltyPoints: 15,
    priority: "medium"
  },
  {
    ruleId: "GEO-004",
    ruleName: "Low Entity Schema Density",
    category: "geo",
    description: "No JSON-LD schema entities detected on the page",
    whyItMatters: "AI search engines map content to conceptual entities using structured data. Without schema markup, your content lacks the machine-readable signals needed for AI models to properly categorize and cite your site.",
    detectionKey: "ai_visibility.entityCoverage.schemaMarkupCount",
    detectionCondition: { operator: "equals", value: 0 },
    recommendation: "Add schema.org JSON-LD entities that describe your business, products, or content.",
    implementationSteps: [
      "Identify core entities on your page (Organization, Person, Product, Service, etc.).",
      "Create JSON-LD blocks for each entity with complete properties.",
      "Use @id references to link related entities together.",
      "Validate all schema with Google's Rich Results Test."
    ],
    aiPromptTemplate: "Generate comprehensive Schema.org JSON-LD for the entities on {url}. The site is a {siteType} in the {industry} industry.",
    expectedResult: "AI models can accurately categorize and cite your content based on structured entity data.",
    seoImpact: "Medium",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Medium",
    estimatedFixTime: "20 minutes",
    confidenceLevel: 90,
    evidenceSource: "Schema.org — Getting Started",
    evidenceUrl: "https://schema.org/docs/gs.html",
    referenceType: "Schema.org",
    penaltyPoints: 10,
    priority: "medium"
  }
];
