import { IKBRule } from "@/types/knowledge-base";

export const googleVisibilityRules: IKBRule[] = [
  {
    ruleId: "GVIS-001",
    ruleName: "Entire Site Blocked in robots.txt",
    category: "google_visibility",
    description: "robots.txt contains Disallow: / blocking all crawlers from the entire site",
    whyItMatters: "A wildcard block rule prevents Googlebot from accessing any page on your domain. This means zero pages will be indexed and your site will not appear in any search results.",
    detectionKey: "google_visibility.crawlability.isFullyBlocked",
    detectionCondition: { operator: "equals", value: true },
    recommendation: "Remove the wildcard Disallow rule and replace with specific rules for private paths only.",
    implementationSteps: [
      "Open your robots.txt file.",
      "Remove 'Disallow: /' or 'Disallow: /*' under the wildcard user-agent.",
      "Replace with 'Allow: /' to permit full access.",
      "Add specific Disallow rules only for genuinely private paths (e.g., /admin/, /api/)."
    ],
    codeSnippet: {
      code: "User-agent: *\nAllow: /\nDisallow: /admin/\nDisallow: /api/\n\nSitemap: https://yourdomain.com/sitemap.xml",
      language: "txt"
    },
    aiPromptTemplate: "Fix my robots.txt at {url} — it's currently blocking all crawlers. Provide a proper configuration that allows search engine access while protecting private paths.",
    expectedResult: "Googlebot can access and index your site pages, making them visible in search results.",
    seoImpact: "Critical",
    googleVisibilityImpact: "Critical",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Critical",
    difficulty: "Easy",
    estimatedFixTime: "2 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Robots.txt Introduction",
    evidenceUrl: "https://developers.google.com/search/docs/crawling-indexing/robots/intro",
    referenceType: "Google Search Central",
    penaltyPoints: 45,
    priority: "critical"
  },
  {
    ruleId: "GVIS-002",
    ruleName: "Missing Canonical Tag",
    category: "google_visibility",
    description: "No canonical link element found on the page",
    whyItMatters: "Canonical tags tell Google which URL version is the primary/preferred version of a page. Without them, URL parameters, trailing slashes, and protocol variations can create duplicate content that dilutes ranking signals.",
    detectionKey: "google_visibility.canonical.canonical",
    detectionCondition: { operator: "missing", value: null },
    recommendation: "Add a canonical link tag pointing to the preferred URL of each page.",
    implementationSteps: [
      "Add <link rel=\"canonical\"> in the <head> of every page.",
      "Set the href to the absolute URL of the preferred version.",
      "Ensure the canonical URL matches the actual page URL (self-referencing canonical).",
      "Make sure the canonical page returns a 200 status code."
    ],
    codeSnippet: {
      code: '<link rel="canonical" href="https://yourdomain.com/current-page/" />',
      language: "html"
    },
    aiPromptTemplate: "Add self-referencing canonical tags to my {framework} website. Include implementation for dynamic pages.",
    expectedResult: "Google consolidates ranking signals to the preferred URL, preventing duplicate content issues.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Low",
    difficulty: "Easy",
    estimatedFixTime: "3 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Consolidate Duplicate URLs",
    evidenceUrl: "https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls",
    referenceType: "Google Search Central",
    penaltyPoints: 12,
    priority: "high"
  },
  {
    ruleId: "GVIS-003",
    ruleName: "Soft 404 Page Detected",
    category: "google_visibility",
    description: "Page returns 200 OK status but contains 'page not found' content",
    whyItMatters: "Soft 404s waste crawl budget because Googlebot visits pages that return success codes but have no real content. This prevents Google from spending time on your actual content pages.",
    detectionKey: "google_visibility.status.isSoft404",
    detectionCondition: { operator: "equals", value: true },
    recommendation: "Return proper HTTP 404 or 410 status codes for truly missing pages.",
    implementationSteps: [
      "Configure your server to return 404 Not Found for pages that don't exist.",
      "Create a helpful custom 404 page with navigation links.",
      "Use 410 Gone for permanently removed content.",
      "Monitor Google Search Console for soft 404 reports."
    ],
    aiPromptTemplate: "Fix soft 404 issues on my {framework} website. Configure proper HTTP status codes for missing pages and create a helpful 404 page.",
    expectedResult: "Google stops wasting crawl budget on non-existent pages.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Low",
    difficulty: "Medium",
    estimatedFixTime: "20 minutes",
    confidenceLevel: 95,
    evidenceSource: "Google Search Central — Soft 404 Errors",
    evidenceUrl: "https://developers.google.com/search/docs/crawling-indexing/http-network-errors#soft-404-errors",
    referenceType: "Google Search Central",
    penaltyPoints: 25,
    priority: "high"
  },
  {
    ruleId: "GVIS-004",
    ruleName: "Duplicate Page Titles",
    category: "google_visibility",
    description: "Multiple pages share identical title tags",
    whyItMatters: "Duplicate titles confuse Google about which page should rank for a given query, causing your pages to compete against each other (keyword cannibalization) and diluting overall search performance.",
    detectionKey: "google_visibility.duplicateCheck.duplicatePagesCount",
    detectionCondition: { operator: "greater_than", value: 0 },
    recommendation: "Make every page title unique and descriptive of that specific page's content.",
    implementationSteps: [
      "Audit all page titles across your site.",
      "Identify pages with identical or very similar titles.",
      "Rewrite each title to uniquely describe that page's content.",
      "Include page-specific keywords in each title."
    ],
    aiPromptTemplate: "My site has duplicate title tags across pages. Help me write unique, SEO-optimized titles for each page: {pages}",
    expectedResult: "Each page has a unique title, eliminating keyword cannibalization.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Medium",
    estimatedFixTime: "30 minutes",
    confidenceLevel: 95,
    evidenceSource: "Google Search Central — Unique Page Titles",
    evidenceUrl: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide#uniquepagetitles",
    referenceType: "Google Search Central",
    penaltyPoints: 12,
    priority: "medium"
  },
  {
    ruleId: "GVIS-005",
    ruleName: "Missing Sitemap Validation",
    category: "google_visibility",
    description: "No sitemap references detected for search engine crawlers",
    whyItMatters: "Sitemaps are the primary way to tell Google about all the pages on your site. Without one, Google relies solely on crawling internal links, which may miss deep or orphaned pages.",
    detectionKey: "google_visibility.sitemap.count",
    detectionCondition: { operator: "equals", value: 0 },
    recommendation: "Create and submit an XML sitemap to Google Search Console.",
    implementationSteps: [
      "Generate an XML sitemap with all indexable pages.",
      "Deploy it at /sitemap.xml on your domain root.",
      "Reference it in your robots.txt file.",
      "Submit it in Google Search Console under Sitemaps."
    ],
    codeSnippet: {
      code: "Sitemap: https://yourdomain.com/sitemap.xml",
      language: "txt"
    },
    aiPromptTemplate: "Generate a complete XML sitemap for {url} and explain how to submit it to Google Search Console.",
    expectedResult: "Google discovers and indexes all your important pages through the sitemap.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "5 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Sitemaps Overview",
    evidenceUrl: "https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview",
    referenceType: "Google Search Central",
    penaltyPoints: 15,
    priority: "high"
  }
];
