import { IKBRule } from "@/types/knowledge-base";

export const performanceRules: IKBRule[] = [
  {
    ruleId: "PERF-001",
    ruleName: "Response Compression Disabled",
    category: "performance",
    description: "Server responses lack Gzip or Brotli content encoding",
    whyItMatters: "Text compression reduces transfer sizes by 60-80%. Without it, users download much larger files, increasing page load time and degrading Core Web Vitals scores that Google uses for ranking.",
    detectionKey: "performance.compression.isCompressed",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Enable Gzip or Brotli compression on your server for text-based assets.",
    implementationSteps: [
      "Check your hosting provider's compression settings.",
      "Enable Gzip or Brotli for HTML, CSS, JS, SVG, and JSON content types.",
      "Verify with curl -H 'Accept-Encoding: gzip' -I yourdomain.com.",
      "Prefer Brotli over Gzip when available (15-25% better compression)."
    ],
    codeSnippet: {
      code: "# Nginx example\ngzip on;\ngzip_types text/plain text/css application/json application/javascript text/xml;\ngzip_min_length 256;",
      language: "nginx"
    },
    aiPromptTemplate: "Configure text compression (Brotli/Gzip) for my {framework} application deployed on {hosting}.",
    expectedResult: "60-80% reduction in transfer size, faster page loads, and improved Core Web Vitals.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Medium",
    estimatedFixTime: "20 minutes",
    confidenceLevel: 100,
    evidenceSource: "web.dev — Reduce Network Payloads Using Text Compression",
    evidenceUrl: "https://web.dev/articles/reduce-network-payloads-using-text-compression",
    referenceType: "web.dev",
    penaltyPoints: 15,
    priority: "high"
  },
  {
    ruleId: "PERF-002",
    ruleName: "Heavy HTML Payload",
    category: "performance",
    description: "HTML document exceeds 200KB in size",
    whyItMatters: "Large HTML documents take longer to parse and render, directly impacting First Contentful Paint (FCP) and Largest Contentful Paint (LCP). The Chrome team recommends keeping DOM size under 1500 nodes.",
    detectionKey: "performance.payload.htmlLengthBytes",
    detectionCondition: { operator: "greater_than", value: 200000 },
    recommendation: "Reduce HTML payload by removing unused code, externalizing inline resources, and optimizing DOM structure.",
    implementationSteps: [
      "Audit the page for inline CSS and JavaScript — move to external files.",
      "Remove commented-out HTML code and unnecessary whitespace.",
      "Implement lazy loading for below-the-fold content.",
      "Consider server-side pagination for large content lists."
    ],
    aiPromptTemplate: "My page HTML is {size}KB. Help me identify what can be removed, externalized, or lazy-loaded to reduce the DOM size.",
    expectedResult: "Faster HTML parsing, improved FCP/LCP metrics, and better mobile performance.",
    seoImpact: "Medium",
    googleVisibilityImpact: "Medium",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Low",
    difficulty: "Hard",
    estimatedFixTime: "1 hour",
    confidenceLevel: 90,
    evidenceSource: "Chrome DevTools — DOM Size Recommendations",
    evidenceUrl: "https://developer.chrome.com/docs/lighthouse/performance/dom-size",
    referenceType: "Chromium Documentation",
    penaltyPoints: 10,
    priority: "medium"
  },
  {
    ruleId: "PERF-003",
    ruleName: "Render-Blocking Scripts",
    category: "performance",
    description: "JavaScript files loaded without async or defer attributes block page rendering",
    whyItMatters: "Render-blocking scripts pause HTML parsing until they download and execute. This directly delays First Contentful Paint (FCP), the moment users see content on screen.",
    detectionKey: "performance.scripts.blockingScripts",
    detectionCondition: { operator: "greater_than", value: 0 },
    recommendation: "Add defer or async attributes to non-critical script tags.",
    implementationSteps: [
      "Identify script tags in the <head> without async or defer attributes.",
      "Add 'defer' for scripts that need DOM access but can load later.",
      "Add 'async' for independent scripts (analytics, ads).",
      "Move non-essential scripts to the bottom of <body>."
    ],
    codeSnippet: {
      code: '<!-- Before -->\n<script src="/app.js"></script>\n\n<!-- After -->\n<script src="/app.js" defer></script>',
      language: "html"
    },
    aiPromptTemplate: "Audit the script loading strategy for {url} and recommend which scripts should use defer, async, or be moved to body end.",
    expectedResult: "Faster First Contentful Paint by unblocking the HTML parser.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 100,
    evidenceSource: "web.dev — Eliminate Render-Blocking Resources",
    evidenceUrl: "https://web.dev/articles/render-blocking-resources",
    referenceType: "web.dev",
    penaltyPoints: 12,
    priority: "high"
  },
  {
    ruleId: "PERF-004",
    ruleName: "Suboptimal Largest Contentful Paint (LCP)",
    category: "performance",
    description: "Estimated LCP exceeds the 2.5-second threshold",
    whyItMatters: "LCP is a Core Web Vital that measures when the main content becomes visible. Google uses it as a ranking signal. Pages with LCP over 2.5 seconds are considered to have poor user experience.",
    detectionKey: "performance.coreWebVitals.lcp",
    detectionCondition: { operator: "greater_than", value: 2500 },
    recommendation: "Optimize LCP by preloading key resources and reducing server response time.",
    implementationSteps: [
      "Identify the LCP element (usually the largest image or text block above the fold).",
      "Preload the LCP image with <link rel=\"preload\">.",
      "Optimize image format (use WebP/AVIF) and size.",
      "Reduce server response time (TTFB) through caching.",
      "Defer non-critical third-party scripts."
    ],
    codeSnippet: {
      code: '<link rel="preload" fetchpriority="high" as="image" href="/hero-image.webp" type="image/webp" />',
      language: "html"
    },
    aiPromptTemplate: "My page at {url} has an LCP of {lcp}ms. Help me optimize it to under 2.5 seconds. The LCP element is {element}.",
    expectedResult: "LCP under 2.5 seconds, qualifying for 'Good' Core Web Vitals status.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Hard",
    estimatedFixTime: "2 hours",
    confidenceLevel: 85,
    evidenceSource: "web.dev — Largest Contentful Paint",
    evidenceUrl: "https://web.dev/articles/lcp",
    referenceType: "web.dev",
    penaltyPoints: 10,
    priority: "medium"
  }
];
