import { IKBRule } from "@/types/knowledge-base";

export const securityRules: IKBRule[] = [
  {
    ruleId: "SEC-001",
    ruleName: "Not Using HTTPS",
    category: "security",
    description: "Website is served over insecure HTTP instead of HTTPS",
    whyItMatters: "Google confirmed HTTPS as a ranking signal in 2014. Browsers mark HTTP sites as 'Not Secure', and unencrypted connections allow attackers to intercept user data.",
    detectionKey: "security.https.active",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Enable HTTPS with a valid SSL/TLS certificate.",
    implementationSteps: [
      "Obtain an SSL/TLS certificate (free via Let's Encrypt, or from your hosting provider).",
      "Install the certificate on your web server.",
      "Configure HTTP-to-HTTPS redirects (301 redirects).",
      "Update all internal links and resources to use HTTPS.",
      "Verify in Google Search Console."
    ],
    aiPromptTemplate: "Help me configure HTTPS for my website at {url} running on {framework}. Include server configuration and redirect setup.",
    expectedResult: "Secure browsing experience, improved search rankings, and no 'Not Secure' browser warnings.",
    seoImpact: "Critical",
    googleVisibilityImpact: "Critical",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "None",
    securityImpact: "Critical",
    businessImpact: "Critical",
    difficulty: "Medium",
    estimatedFixTime: "1 hour",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — HTTPS as a Ranking Signal",
    evidenceUrl: "https://developers.google.com/search/docs/crawling-indexing/https",
    referenceType: "Google Search Central",
    penaltyPoints: 50,
    priority: "critical"
  },
  {
    ruleId: "SEC-002",
    ruleName: "Missing Content Security Policy (CSP)",
    category: "security",
    description: "No Content-Security-Policy header found in server response",
    whyItMatters: "CSP prevents cross-site scripting (XSS) and code injection attacks by specifying which sources are allowed to load scripts, styles, and other resources on your page.",
    detectionKey: "security.headers.hasCsp",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Add a Content-Security-Policy header to your server configuration.",
    implementationSteps: [
      "Audit all script, style, image, and font sources used by your site.",
      "Create a CSP policy that allows only trusted sources.",
      "Start with Report-Only mode to test without breaking anything.",
      "Deploy the final policy as a response header."
    ],
    codeSnippet: {
      code: "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:;",
      language: "http"
    },
    aiPromptTemplate: "Generate a Content-Security-Policy header for my website at {url} built with {framework}. List all required source exceptions.",
    expectedResult: "Protection against XSS and code injection attacks.",
    seoImpact: "Low",
    googleVisibilityImpact: "Low",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "High",
    businessImpact: "High",
    difficulty: "Hard",
    estimatedFixTime: "2 hours",
    confidenceLevel: 100,
    evidenceSource: "OWASP — Content Security Policy",
    evidenceUrl: "https://owasp.org/www-project-secure-headers/#content-security-policy",
    referenceType: "OWASP",
    penaltyPoints: 15,
    priority: "high"
  },
  {
    ruleId: "SEC-003",
    ruleName: "Missing HSTS Header",
    category: "security",
    description: "No Strict-Transport-Security header found on HTTPS site",
    whyItMatters: "HSTS forces browsers to always connect via HTTPS, even if the user types HTTP. This prevents SSL-stripping attacks where an attacker downgrades the connection to intercept data.",
    detectionKey: "security.headers.hasHsts",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Add Strict-Transport-Security header with a long max-age.",
    implementationSteps: [
      "Add the HSTS header to your server configuration.",
      "Start with a short max-age (e.g., 3600) to test.",
      "Gradually increase to 2 years (63072000 seconds).",
      "Add includeSubDomains and preload when ready."
    ],
    codeSnippet: {
      code: "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload",
      language: "http"
    },
    aiPromptTemplate: "Configure HSTS header for my website at {url}. Explain the implications of includeSubDomains and preload directives.",
    expectedResult: "Browsers enforce HTTPS-only connections, preventing downgrade attacks.",
    seoImpact: "Low",
    googleVisibilityImpact: "Low",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "High",
    businessImpact: "Medium",
    difficulty: "Medium",
    estimatedFixTime: "30 minutes",
    confidenceLevel: 100,
    evidenceSource: "OWASP — HTTP Strict Transport Security",
    evidenceUrl: "https://owasp.org/www-project-secure-headers/#http-strict-transport-security",
    referenceType: "OWASP",
    penaltyPoints: 10,
    priority: "high"
  },
  {
    ruleId: "SEC-004",
    ruleName: "Missing X-Frame-Options Header",
    category: "security",
    description: "No X-Frame-Options header found in server response",
    whyItMatters: "X-Frame-Options prevents your site from being embedded in iframes on malicious sites, protecting users from clickjacking attacks where invisible frames trick users into clicking on hidden elements.",
    detectionKey: "security.headers.hasXFrame",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Set X-Frame-Options to DENY or SAMEORIGIN.",
    implementationSteps: [
      "Add X-Frame-Options header to your server configuration.",
      "Set value to DENY (blocks all framing) or SAMEORIGIN (allows same-origin framing only).",
      "Test that your site still works properly in any legitimate iframe contexts."
    ],
    codeSnippet: {
      code: "X-Frame-Options: SAMEORIGIN",
      language: "http"
    },
    aiPromptTemplate: "Add X-Frame-Options header to my {framework} server configuration. Should I use DENY or SAMEORIGIN?",
    expectedResult: "Protection against clickjacking attacks.",
    seoImpact: "None",
    googleVisibilityImpact: "None",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "Medium",
    businessImpact: "Low",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 100,
    evidenceSource: "OWASP — Clickjacking Defense",
    evidenceUrl: "https://owasp.org/www-community/attacks/Clickjacking",
    referenceType: "OWASP",
    penaltyPoints: 8,
    priority: "medium"
  },
  {
    ruleId: "SEC-005",
    ruleName: "Missing security.txt File",
    category: "security",
    description: "No security.txt file found at /.well-known/security.txt or domain root",
    whyItMatters: "security.txt (RFC 9116) provides a standardized way for security researchers to report vulnerabilities. Having one shows security maturity and helps ensure responsible disclosure.",
    detectionKey: "security.securityTxt.exists",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Create a security.txt file with your security contact information.",
    implementationSteps: [
      "Create a security.txt file.",
      "Place it at /.well-known/security.txt (preferred) or domain root.",
      "Include at minimum: Contact, Expires, and Preferred-Languages fields.",
      "Optionally sign it with PGP."
    ],
    codeSnippet: {
      code: "Contact: mailto:security@yourdomain.com\nExpires: 2027-01-01T00:00:00.000Z\nPreferred-Languages: en",
      language: "txt",
      filename: "security.txt"
    },
    aiPromptTemplate: "Generate a security.txt file for my organization. Our security email is {email}.",
    expectedResult: "Security researchers can easily find your disclosure policy and report vulnerabilities responsibly.",
    seoImpact: "None",
    googleVisibilityImpact: "None",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "Low",
    businessImpact: "Low",
    difficulty: "Easy",
    estimatedFixTime: "5 minutes",
    confidenceLevel: 100,
    evidenceSource: "RFC 9116 — A File Format to Aid in Security Vulnerability Disclosure",
    evidenceUrl: "https://www.rfc-editor.org/rfc/rfc9116",
    referenceType: "RFC Standard",
    penaltyPoints: 5,
    priority: "low"
  },
  {
    ruleId: "SEC-006",
    ruleName: "Mixed Content Detected",
    category: "security",
    description: "HTTPS page loads scripts or assets over insecure HTTP",
    whyItMatters: "Mixed content on an HTTPS page allows attackers to intercept and modify insecure resources, potentially injecting malicious code. Browsers may block mixed content, breaking functionality.",
    detectionKey: "security.mixedContent.count",
    detectionCondition: { operator: "greater_than", value: 0 },
    recommendation: "Update all resource URLs to use HTTPS or protocol-relative paths.",
    implementationSteps: [
      "Search your HTML for http:// references in script src, img src, link href attributes.",
      "Change them to https:// or use protocol-relative URLs (//).",
      "Check CSS files for http:// references in url() values.",
      "Test the page to ensure no mixed content warnings remain."
    ],
    aiPromptTemplate: "Find and fix all mixed content issues on my page at {url}. List all HTTP resources that need to be updated to HTTPS.",
    expectedResult: "Clean HTTPS page with no browser mixed content warnings.",
    seoImpact: "Medium",
    googleVisibilityImpact: "Medium",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "High",
    businessImpact: "High",
    difficulty: "Medium",
    estimatedFixTime: "30 minutes",
    confidenceLevel: 100,
    evidenceSource: "web.dev — What Is Mixed Content?",
    evidenceUrl: "https://web.dev/articles/what-is-mixed-content",
    referenceType: "web.dev",
    penaltyPoints: 15,
    priority: "high"
  }
];
