import { IKBRule } from "@/types/knowledge-base";

export const seoRules: IKBRule[] = [
  {
    ruleId: "SEO-001",
    ruleName: "Missing robots.txt",
    category: "seo",
    description: "No robots.txt file found at the domain root",
    whyItMatters: "Robots.txt tells search engine crawlers which parts of your site they can access. Without it, crawlers may waste budget on low-value pages or index private directories.",
    detectionKey: "seo.robotsTxt.exists",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Create a robots.txt file at your domain root with default crawl rules and a sitemap reference.",
    implementationSteps: [
      "Create a plain text file named 'robots.txt' in your public/root directory.",
      "Add default crawl rules: 'User-agent: *' followed by 'Allow: /'.",
      "Add your sitemap reference: 'Sitemap: https://yourdomain.com/sitemap.xml'.",
      "Deploy and verify by visiting yourdomain.com/robots.txt."
    ],
    codeSnippet: {
      code: "User-agent: *\nAllow: /\n\nSitemap: https://yourdomain.com/sitemap.xml",
      language: "txt",
      filename: "robots.txt"
    },
    aiPromptTemplate: "Generate a robots.txt file for my website at {url}. Include standard Allow rules and a sitemap reference. The site is built with {framework}.",
    expectedResult: "Search engines will efficiently crawl your site following your specified rules, preserving crawl budget for important pages.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "Low",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "5 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Robots.txt Specifications",
    evidenceUrl: "https://developers.google.com/search/docs/crawling-indexing/robots/intro",
    referenceType: "Google Search Central",
    penaltyPoints: 10,
    priority: "high"
  },
  {
    ruleId: "SEO-002",
    ruleName: "Missing XML Sitemap",
    category: "seo",
    description: "No XML sitemap references found on the domain",
    whyItMatters: "XML sitemaps help Google and other search engines discover and index all important URLs on your website. Without one, deep pages may never be found.",
    detectionKey: "seo.sitemaps.count",
    detectionCondition: { operator: "equals", value: 0 },
    recommendation: "Generate and deploy an XML sitemap containing all indexable pages.",
    implementationSteps: [
      "Generate an XML sitemap listing all indexable page URLs.",
      "Upload it to your website root as /sitemap.xml.",
      "Reference the sitemap in your robots.txt file.",
      "Submit it in Google Search Console."
    ],
    codeSnippet: {
      code: '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url>\n    <loc>https://yourdomain.com/</loc>\n  </url>\n</urlset>',
      language: "xml",
      filename: "sitemap.xml"
    },
    aiPromptTemplate: "Generate an XML sitemap for my website at {url}. Include the homepage and all major pages.",
    expectedResult: "Google will discover and index all important pages on your site more quickly.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "Medium",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Sitemaps Overview",
    evidenceUrl: "https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview",
    referenceType: "Google Search Central",
    penaltyPoints: 10,
    priority: "high"
  },
  {
    ruleId: "SEO-003",
    ruleName: "Missing Title Tag",
    category: "seo",
    description: "No <title> element found in the page HTML head",
    whyItMatters: "The title tag is the most prominent element shown in Google search results and is a confirmed ranking factor. Missing it means Google will auto-generate a title, which may not represent your page well.",
    detectionKey: "seo.title.exists",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Add a descriptive, keyword-rich <title> tag to every page.",
    implementationSteps: [
      "Add a <title> element inside the <head> section of your HTML.",
      "Write a descriptive title between 30-65 characters.",
      "Place the primary keyword near the beginning of the title.",
      "Make each page title unique across the site."
    ],
    codeSnippet: {
      code: "<head>\n  <title>Primary Keyword - Secondary Keyword | Brand Name</title>\n</head>",
      language: "html"
    },
    aiPromptTemplate: "Write an SEO-optimized title tag for the page at {url}. The page is about {topic}. Keep it between 30-65 characters.",
    expectedResult: "Your page will display a compelling, keyword-rich title in search results, improving click-through rates.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "Medium",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Easy",
    estimatedFixTime: "2 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Title Links",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/title-link",
    referenceType: "Google Search Central",
    penaltyPoints: 25,
    priority: "critical"
  },
  {
    ruleId: "SEO-004",
    ruleName: "Suboptimal Title Tag Length",
    category: "seo",
    description: "Title tag length is outside the recommended 30-65 character range",
    whyItMatters: "Titles under 30 characters often lack sufficient keywords. Titles over 65 characters get truncated in search results, hiding important information from users.",
    detectionKey: "seo.title.length",
    detectionCondition: { operator: "greater_than", value: 65 },
    recommendation: "Rewrite the page title to be between 30 and 65 characters, placing primary keywords near the beginning.",
    implementationSteps: [
      "Review the current title tag content and character count.",
      "Rewrite to fit within 30-65 characters.",
      "Front-load the most important keyword.",
      "Test the new title in Google's SERP preview tools."
    ],
    codeSnippet: {
      code: "<title>Target Keyword — Secondary Keyword | Brand</title>",
      language: "html"
    },
    aiPromptTemplate: "Rewrite this title tag to be between 30-65 characters while keeping the primary keyword first: \"{currentTitle}\"",
    expectedResult: "Full title displays in search results without truncation, improving click-through rates.",
    seoImpact: "Medium",
    googleVisibilityImpact: "Medium",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "3 minutes",
    confidenceLevel: 95,
    evidenceSource: "Google Search Central — Title Links",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/title-link",
    referenceType: "Google Search Central",
    penaltyPoints: 8,
    priority: "medium"
  },
  {
    ruleId: "SEO-005",
    ruleName: "Missing Meta Description",
    category: "seo",
    description: "No meta description tag found in the HTML head",
    whyItMatters: "Meta descriptions appear as the snippet text in search results. While not a direct ranking factor, they significantly affect click-through rates. Without one, Google will auto-generate a snippet which may not be compelling.",
    detectionKey: "seo.metaDescription.exists",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Add a meta description tag with a compelling summary of the page content (110-160 characters).",
    implementationSteps: [
      "Add a <meta name=\"description\"> tag in the <head> section.",
      "Write a compelling summary in 110-160 characters.",
      "Include a call-to-action (e.g., 'Learn more', 'Get started').",
      "Make each page's description unique."
    ],
    codeSnippet: {
      code: '<meta name="description" content="Compelling page summary with keywords and a clear call-to-action. Keep between 110-160 characters." />',
      language: "html"
    },
    aiPromptTemplate: "Write a compelling meta description for the page at {url}. The page is about {topic}. Keep it between 110-160 characters with a call-to-action.",
    expectedResult: "Search results will display your custom snippet, improving click-through rates from Google.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Easy",
    estimatedFixTime: "2 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Control Your Snippets",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/snippet",
    referenceType: "Google Search Central",
    penaltyPoints: 15,
    priority: "high"
  },
  {
    ruleId: "SEO-006",
    ruleName: "Missing H1 Tag",
    category: "seo",
    description: "No H1 heading element found on the page",
    whyItMatters: "The H1 tag signals the main topic of your page to search engines and screen readers. Missing it makes it harder for crawlers to understand page content hierarchy.",
    detectionKey: "seo.headings.h1Count",
    detectionCondition: { operator: "equals", value: 0 },
    recommendation: "Add a single, descriptive H1 heading that clearly states the main topic of the page.",
    implementationSteps: [
      "Identify the primary topic/title of your page body content.",
      "Wrap it in an <h1> element.",
      "Ensure only one H1 exists per page.",
      "Use H2-H6 for sub-sections."
    ],
    codeSnippet: {
      code: "<h1>Main Page Topic with Primary Keyword</h1>",
      language: "html"
    },
    aiPromptTemplate: "Write an SEO-optimized H1 heading for the page at {url}. The page is about {topic}.",
    expectedResult: "Search engines and screen readers can clearly identify the main topic of your page.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "Medium",
    accessibilityImpact: "Medium",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Easy",
    estimatedFixTime: "5 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Heading Elements",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/title-link#heading-elements",
    referenceType: "Google Search Central",
    penaltyPoints: 20,
    priority: "critical"
  },
  {
    ruleId: "SEO-007",
    ruleName: "Multiple H1 Tags",
    category: "seo",
    description: "More than one H1 heading element found on the page",
    whyItMatters: "While HTML5 technically allows multiple H1s, using a single H1 per page provides the clearest topical signal to search engines and maintains proper document outline.",
    detectionKey: "seo.headings.h1Count",
    detectionCondition: { operator: "greater_than", value: 1 },
    recommendation: "Keep one H1 as the primary heading. Convert other H1s to H2 or H3 elements.",
    implementationSteps: [
      "Identify which H1 best represents the main page topic.",
      "Keep that as the sole H1.",
      "Convert remaining H1 elements to H2 or H3 as appropriate.",
      "Verify heading hierarchy follows logical nesting."
    ],
    aiPromptTemplate: "My page has multiple H1 tags. Help me restructure the heading hierarchy so there is exactly one H1.",
    expectedResult: "Clear document outline with a single main heading, improving topical focus for crawlers.",
    seoImpact: "Medium",
    googleVisibilityImpact: "Medium",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "Medium",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Medium",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 90,
    evidenceSource: "HTML Living Standard — Headings and Outlines",
    evidenceUrl: "https://html.spec.whatwg.org/multipage/sections.html#headings-and-outlines",
    referenceType: "W3C",
    penaltyPoints: 10,
    priority: "medium"
  },
  {
    ruleId: "SEO-008",
    ruleName: "Heading Hierarchy Skip",
    category: "seo",
    description: "Heading levels are skipped (e.g., H1 followed by H3 without H2)",
    whyItMatters: "Skipping heading levels breaks the logical document outline, confuses screen readers, and makes it harder for search engines to understand content structure.",
    detectionKey: "seo.headingHierarchy.orderly",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Fix the heading hierarchy so levels increase sequentially (H1 → H2 → H3).",
    implementationSteps: [
      "Audit all heading tags on the page in document order.",
      "Ensure H2 follows H1, H3 follows H2, etc.",
      "Never skip a level (e.g., no H1 directly to H3).",
      "Use headings for structure, not for visual styling."
    ],
    aiPromptTemplate: "Restructure the heading hierarchy on this page to follow proper sequential nesting (H1 → H2 → H3).",
    expectedResult: "Proper document outline that is accessible and easily parsed by search engines.",
    seoImpact: "Medium",
    googleVisibilityImpact: "Medium",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "High",
    securityImpact: "None",
    businessImpact: "None",
    difficulty: "Medium",
    estimatedFixTime: "15 minutes",
    confidenceLevel: 95,
    evidenceSource: "WCAG 2.1 — Info and Relationships (1.3.1)",
    evidenceUrl: "https://www.w3.org/TR/WCAG21/#info-and-relationships",
    referenceType: "WCAG 2.1",
    penaltyPoints: 8,
    priority: "medium"
  },
  {
    ruleId: "SEO-009",
    ruleName: "Missing Image Alt Text",
    category: "seo",
    description: "One or more images lack descriptive alt text attributes",
    whyItMatters: "Alt text provides textual descriptions of images for screen readers and search crawlers. It is also used by Google Image Search for indexing and is an accessibility requirement under WCAG.",
    detectionKey: "seo.images.missingAlt",
    detectionCondition: { operator: "greater_than", value: 0 },
    recommendation: "Add descriptive alt text to every meaningful image on the page.",
    implementationSteps: [
      "Locate all images without alt attributes.",
      "Write concise, descriptive alt text for each image.",
      "Include relevant keywords naturally (avoid keyword stuffing).",
      "Use empty alt=\"\" only for purely decorative images."
    ],
    codeSnippet: {
      code: '<img src="/product.jpg" alt="Red running shoes with cushioned sole - Nike Air Max" />',
      language: "html"
    },
    aiPromptTemplate: "Write descriptive alt text for the images on the page at {url}. Make them concise, descriptive, and include relevant keywords.",
    expectedResult: "Improved image search visibility and accessibility compliance.",
    seoImpact: "Medium",
    googleVisibilityImpact: "Medium",
    aiVisibilityImpact: "Low",
    accessibilityImpact: "High",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Image Best Practices",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/google-images#descriptive-alt-text",
    referenceType: "Google Search Central",
    penaltyPoints: 12,
    priority: "medium"
  },
  {
    ruleId: "SEO-010",
    ruleName: "Weak Link Anchor Text",
    category: "seo",
    description: "Links use generic anchor text like 'click here' or 'read more'",
    whyItMatters: "Anchor text tells search engines what the linked page is about. Generic text like 'click here' provides no topical signal, wasting valuable internal linking equity.",
    detectionKey: "seo.anchorText.weakAnchorsCount",
    detectionCondition: { operator: "greater_than", value: 0 },
    recommendation: "Replace generic anchor text with descriptive, keyword-aligned text that describes the destination page.",
    implementationSteps: [
      "Search your HTML for links with generic text ('click here', 'read more', 'link').",
      "Replace with descriptive text that tells readers what they'll find.",
      "Example: Replace 'Click here for our SEO guide' with 'Read our complete SEO guide'."
    ],
    aiPromptTemplate: "Rewrite these generic anchor texts to be descriptive and keyword-rich: {anchors}",
    expectedResult: "Internal links pass relevant topical signals to destination pages, boosting their search rankings.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "Medium",
    accessibilityImpact: "Medium",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Easy",
    estimatedFixTime: "10 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Link Best Practices",
    evidenceUrl: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide#use-links-wisely",
    referenceType: "Google Search Central",
    penaltyPoints: 10,
    priority: "medium"
  },
  {
    ruleId: "SEO-011",
    ruleName: "Missing Social Meta Tags",
    category: "seo",
    description: "Open Graph or Twitter Card meta tags are not present",
    whyItMatters: "Social meta tags control how your URL appears when shared on Facebook, Twitter, LinkedIn, and messaging apps. Without them, platforms generate unpredictable previews.",
    detectionKey: "seo.socialMeta.hasOgTitle",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Add Open Graph (og:) and Twitter Card meta tags to your pages.",
    implementationSteps: [
      "Add og:title, og:description, og:image, og:url meta tags.",
      "Add twitter:card, twitter:title, twitter:description meta tags.",
      "Use high-quality images (1200x630px recommended for og:image).",
      "Test with Facebook Sharing Debugger and Twitter Card Validator."
    ],
    codeSnippet: {
      code: '<meta property="og:title" content="Page Title" />\n<meta property="og:description" content="Page description" />\n<meta property="og:image" content="https://yourdomain.com/og-image.jpg" />\n<meta name="twitter:card" content="summary_large_image" />',
      language: "html"
    },
    aiPromptTemplate: "Generate Open Graph and Twitter Card meta tags for the page at {url} about {topic}.",
    expectedResult: "Consistent, branded previews when your URL is shared on social media platforms.",
    seoImpact: "Low",
    googleVisibilityImpact: "Low",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Easy",
    estimatedFixTime: "5 minutes",
    confidenceLevel: 100,
    evidenceSource: "Open Graph Protocol Specification",
    evidenceUrl: "https://ogp.me/",
    referenceType: "Industry Best Practice",
    penaltyPoints: 5,
    priority: "low"
  },
  {
    ruleId: "SEO-012",
    ruleName: "Missing Structured Data",
    category: "seo",
    description: "No JSON-LD structured data markup detected on the page",
    whyItMatters: "Structured data helps Google understand your content and can enable rich results (star ratings, FAQ dropdowns, product cards) in search, dramatically increasing visibility and CTR.",
    detectionKey: "seo.structuredData.count",
    detectionCondition: { operator: "equals", value: 0 },
    recommendation: "Add JSON-LD structured data matching your page content type (Organization, Product, Article, etc.).",
    implementationSteps: [
      "Identify the schema type that matches your page (Organization, Product, Article, LocalBusiness, etc.).",
      "Create a JSON-LD block with required and recommended properties.",
      "Insert it inside a <script type=\"application/ld+json\"> tag.",
      "Validate with Google's Rich Results Test tool."
    ],
    codeSnippet: {
      code: '<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@type": "Organization",\n  "name": "Your Brand",\n  "url": "https://yourdomain.com",\n  "logo": "https://yourdomain.com/logo.png"\n}\n</script>',
      language: "json"
    },
    aiPromptTemplate: "Generate JSON-LD structured data for the page at {url}. The site type is {siteType}. Include all recommended Schema.org properties.",
    expectedResult: "Eligibility for rich results in Google Search, increasing visibility and click-through rates.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Medium",
    estimatedFixTime: "15 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Structured Data Introduction",
    evidenceUrl: "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data",
    referenceType: "Google Search Central",
    penaltyPoints: 12,
    priority: "high"
  },
  {
    ruleId: "SEO-013",
    ruleName: "Thin Content",
    category: "seo",
    description: "Page body contains fewer than 300 words of text content",
    whyItMatters: "Google's Quality Rater Guidelines consider pages with minimal content as 'thin'. These pages struggle to rank because they provide insufficient value to satisfy user search intent.",
    detectionKey: "seo.thinContent.wordCount",
    detectionCondition: { operator: "less_than", value: 300 },
    recommendation: "Expand page content with valuable, original information that thoroughly addresses the topic.",
    implementationSteps: [
      "Analyze the page topic and user search intent.",
      "Add detailed descriptions, explanations, or guides.",
      "Include FAQs, comparison tables, or step-by-step instructions.",
      "Aim for at least 500-800 words of unique, helpful content."
    ],
    aiPromptTemplate: "The page at {url} only has {wordCount} words. Suggest additional content sections that would add value for users searching for {topic}.",
    expectedResult: "Richer content that better satisfies search intent, improving organic rankings.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "High",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "Medium",
    difficulty: "Medium",
    estimatedFixTime: "30 minutes",
    confidenceLevel: 90,
    evidenceSource: "Google Search Central — Creating Helpful Content",
    evidenceUrl: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content",
    referenceType: "Google Search Central",
    penaltyPoints: 15,
    priority: "high"
  },
  {
    ruleId: "SEO-014",
    ruleName: "Page Flagged Noindex",
    category: "seo",
    description: "Page has a noindex robots meta directive preventing indexing",
    whyItMatters: "A noindex directive tells search engines to completely exclude the page from their index. If this is your main landing page, it will not appear in any search results.",
    detectionKey: "seo.indexability.indexable",
    detectionCondition: { operator: "equals", value: false },
    recommendation: "Remove the noindex directive if this page should appear in search results.",
    implementationSteps: [
      "Locate the <meta name=\"robots\"> tag in the HTML head.",
      "Remove 'noindex' from the content attribute.",
      "Replace with 'index, follow' to allow full indexing.",
      "Also check HTTP response headers for X-Robots-Tag: noindex."
    ],
    codeSnippet: {
      code: '<meta name="robots" content="index, follow" />',
      language: "html"
    },
    aiPromptTemplate: "My page at {url} has a noindex directive. Help me determine if it should be indexed and provide the correct robots meta tag.",
    expectedResult: "Page becomes eligible for Google Search indexing and can appear in search results.",
    seoImpact: "High",
    googleVisibilityImpact: "High",
    aiVisibilityImpact: "None",
    accessibilityImpact: "None",
    securityImpact: "None",
    businessImpact: "High",
    difficulty: "Easy",
    estimatedFixTime: "2 minutes",
    confidenceLevel: 100,
    evidenceSource: "Google Search Central — Block Indexing",
    evidenceUrl: "https://developers.google.com/search/docs/crawling-indexing/block-indexing",
    referenceType: "Google Search Central",
    penaltyPoints: 40,
    priority: "critical"
  }
];
